# Generated by Django 3.2.10 on 2022-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='records',
            name='rdate',
            field=models.DateField(),
        ),
    ]
