# Generated by Django 3.2 on 2022-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passwd',
            field=models.CharField(max_length=32),
        ),
    ]
